services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./backend:/backend
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    networks:
      - app_net

  celery:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    env_file:
      - backend/.env
    volumes:
      - ./backend:/backend
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - app_net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_net

volumes:
  redis_data:

networks:
  app_net:
